/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BurgersDeliverySystem;
import javax.swing.*;
/**
 *
 * @author Nedlog
 */
public class OrdersPage extends javax.swing.JFrame {

    /**
     * Creates new form OrdersPage
     */
    public OrdersPage() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDeliveryAddress = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        btnOrderNow = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtpassword1 = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel2.setText("PLACE ORDERS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(28, 54, 200, 30);

        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(28, 102, 54, 14);

        jLabel5.setText("QUANTITY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 270, 90, 20);

        jLabel6.setText("TYPE OF ORDER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(28, 194, 100, 14);

        jLabel7.setText("SIZE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(28, 232, 22, 14);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SMALL", "BIG" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(144, 229, 56, 20);

        jLabel8.setText("DELIVERY ADDRESS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 334, 110, 40);
        getContentPane().add(txtQuantity);
        txtQuantity.setBounds(140, 270, 120, 20);

        jLabel9.setBackground(java.awt.Color.yellow);
        jLabel9.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        jLabel9.setForeground(java.awt.Color.red);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TASTY BURGERS DELIVERY SYSTEM");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 970, 40);
        getContentPane().add(txtDeliveryAddress);
        txtDeliveryAddress.setBounds(150, 320, 150, 100);
        getContentPane().add(txtUserName);
        txtUserName.setBounds(140, 100, 120, 20);

        jLabel10.setText("PASSWORD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(28, 149, 70, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cheese Burger", "Ham Burger", "Beef Burger", "Chicken Burger" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 190, 190, 20);

        btnOrderNow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOrderNow.setText("ORDER NOW");
        btnOrderNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderNowActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrderNow);
        btnOrderNow.setBounds(110, 440, 110, 23);

        jPanel1.setBackground(java.awt.Color.red);
        jPanel1.setLayout(null);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BurgersDeliverySystem/Tasty burger.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(470, 0, 500, 390);
        jPanel1.add(txtpassword1);
        txtpassword1.setBounds(140, 110, 120, 20);

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClose.setText("EXIT");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);
        btnClose.setBounds(720, 400, 110, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 400, 100, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 40, 970, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnOrderNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderNowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderNowActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "You are logging out...");
        this.setVisible(false);
        this.dispose();
       LogoutPage obj2= new LogoutPage();
        obj2.setVisible(true);
        obj2.setSize(971,500);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdersPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOrderNow;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDeliveryAddress;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtpassword1;
    // End of variables declaration//GEN-END:variables
}
