/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programmingschoolgui;

/**
 *
 * @author Nedlog
 */
public class GUIAdditionFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdditionForm
     */
    public GUIAdditionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNum1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNum2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlAnswer = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Enter Num1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(35, 48, 100, 14);

        jtfNum1.setName(""); // NOI18N
        getContentPane().add(jtfNum1);
        jtfNum1.setBounds(160, 50, 120, 20);

        jLabel2.setText("Enter Num2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(35, 99, 70, 30);

        jtfNum2.setName(""); // NOI18N
        getContentPane().add(jtfNum2);
        jtfNum2.setBounds(160, 100, 120, 20);

        jLabel3.setText("Answer");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 70, 20);

        jlAnswer.setName(""); // NOI18N
        getContentPane().add(jlAnswer);
        jlAnswer.setBounds(160, 150, 130, 20);

        btnAdd.setText("Add");
        btnAdd.setName(""); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(130, 210, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String strNum1;
        int num1,num2,sum;
        //Get input values from the two text fields and store in the respective variables
        strNum1=jtfNum1.getText();
        num1=Integer.parseInt(strNum1);
        num2=Integer.parseInt(jtfNum2.getText());
        //Add up the valuees and store in a variable
        sum=num1+num2;
        //Assign the variable value to jlAnswer
        jlAnswer.setText("Answer = "+ sum);
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAdditionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAdditionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAdditionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAdditionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAdditionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlAnswer;
    private javax.swing.JTextField jtfNum1;
    private javax.swing.JTextField jtfNum2;
    // End of variables declaration//GEN-END:variables
}
